spring:
  datasource:
    # 生产环境数据库配置
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}  # 使用环境变量或默认值
    password: ${MYSQL_PASSWORD:root}

logging:
  level:
    root: warn
    com.example.demo: info
  file:
    name: logs/application.log  # 生产环境日志文件